### PR TITLE
`Programming Exercise`: Fix undo crash

### LINKED ISSUE #181: Performing undo after accepting suggested programming feedback crashes the app
Adding a suggested feedback to a programming submission leads to a crash when undone.

Steps
- Open a programming submission for assessment
- Tap on the lightbulb icon on a file with feedback suggestion
- Save the feedback
- Tap the undo button
- The app crashes

### PR DESCRIPTION
**Pull request by terlan98**
Closes #181

### CODE REVIEW

File: Themis/ViewModels/Assessment/Programming/CodeEditorViewModel.swift [hunk 1]
```diff
@@ -122,6 +122,8 @@ class CodeEditorViewModel: ExerciseRendererViewModel {
             }
             appendHighlight(feedbackId: feedbackId, range: range, path: file.path)
         }
+        
+        undoManager.endUndoGrouping() // undo group with addFeedback in AssessmentResult
```
Comment (maximiliansoelch) [inline Themis/ViewModels/Assessment/Programming/CodeEditorViewModel.swift:126]: Wouldn't adding this to the appendHighlight function make more sense?

**Review by maximiliansoelch — COMMENTED** [review]
This comment is also incorrect, right? It should be _undo group with deleteInlineHighlight_.
Screenshot 2023-09-07 at 18 36 17

File: Themis/ViewModels/Assessment/Programming/CodeEditorViewModel.swift (hunk 1 above)
Comment (terlan98) [reply Themis/ViewModels/Assessment/Programming/CodeEditorViewModel.swift:126]: `appendHighlight()` is also used when existing highlights are loaded from the server. Calling `.endUndoGrouping()` would cause a crash in this case since there would be no corresponding `.beginUndoGrouping()` calls.

**Review by maximiliansoelch — APPROVED** [review]
Code changes looks good! 👍
